from __future__ import annotations

from pathlib import Path
from typing import Any, Mapping
import ast
from copy import deepcopy
import re

try:  # PyYAML is preferred when available.
    import yaml as _pyyaml  # type: ignore
except ModuleNotFoundError:  # pragma: no cover - exercised in user environments without PyYAML
    _pyyaml = None  # type: ignore[assignment]


class ConfigError(ValueError):
    """Raised when a project configuration file is invalid."""


PUBLIC_CONFIG_SCHEMA = "public_01_09"

# The scientific modules predate the public 01--09 numbering. New configuration
# files use exactly the same step numbers as the CLI; this table translates that
# public layout into the established runtime keys without changing calculations.
PUBLIC_TO_RUNTIME_STEP_KEYS = {
    "step04": "step05",  # catalytic-region pLDDT
    "step05": "step06",  # PLIP interaction graphs
    "step06": "step07",  # key-residue screening
    "step07": "step08",  # GED classification
    "step08": "step09",  # ligand contact-unit grouping
    "step09": "step10",  # visualization
}


def normalize_project_config(config: Mapping[str, Any]) -> dict[str, Any]:
    """Return the runtime view of either a public or historical config.

    Historical YAML files are left unchanged. Files generated by the current
    CLI/GUI carry ``config_schema: public_01_09`` and are copied into the
    long-established runtime slots used by the scientific modules. Reading an
    old project therefore remains reproducible while new users see one coherent
    Step01--Step09 numbering system.
    """
    normalized = deepcopy(dict(config))
    if str(normalized.get("config_schema", "")).strip().lower() != PUBLIC_CONFIG_SCHEMA:
        return normalized

    public_steps = {
        public_key: deepcopy(normalized.get(public_key, {}))
        for public_key in PUBLIC_TO_RUNTIME_STEP_KEYS
    }
    for public_key, runtime_key in PUBLIC_TO_RUNTIME_STEP_KEYS.items():
        normalized[runtime_key] = public_steps[public_key]
    normalized["_config_layout"] = PUBLIC_CONFIG_SCHEMA
    return normalized


# These migration aliases make historical output directories match the public
# 01--09 workflow. An unrelated custom directory is returned
# unchanged, while old project YAML files are transparently moved to the new
# default on their next run.
LEGACY_OUTPUT_SUBDIR_ALIASES = {
    "05_catalytic_region_plddt_qc": "04_catalytic_region_plddt_qc",
    "06_plip_interaction_graphs": "05_plip_interaction_graphs",
    "07_key_residue_screening": "06_key_residue_screening",
    "08_ged_classification": "07_ged_classification",
    "09_chemical_equivalence": "08_chemical_equivalence",
    "10_class_visualization": "09_class_visualization",
}


def public_output_subdir(value: Any, default: str) -> str:
    """Return a public-numbered output directory, retaining custom names."""
    text = str(value or default).strip()
    return LEGACY_OUTPUT_SUBDIR_ALIASES.get(text, text)


def load_yaml_config(config_path: str | Path) -> dict[str, Any]:
    """Load a project-level YAML configuration file.

    PyYAML is used when it is installed.  A small built-in fallback parser is
    kept for CatConGraph project configs so commands still start in lightweight
    environments where ``pyyaml`` has not been installed yet.  The fallback is
    intentionally conservative: it supports the subset used by CatConGraph
    configs (nested mappings, block lists, inline scalar lists, strings,
    numbers, booleans, and null).

    Paths are intentionally not rewritten here. The recommended usage is to
    run every script from the repository root, so relative paths in the config
    are interpreted relative to the current working directory.
    """
    config_path = Path(config_path)
    if not config_path.exists():
        raise FileNotFoundError(f"Config file not found: {config_path}")

    text = config_path.read_text(encoding="utf-8")
    if _pyyaml is not None:
        cfg = _pyyaml.safe_load(text) or {}
    else:
        cfg = _parse_simple_yaml(text)

    if not isinstance(cfg, dict):
        raise ConfigError("The config file must contain a YAML mapping at top level.")

    cfg = normalize_project_config(cfg)
    cfg["_config_path"] = str(config_path)
    return cfg


def get_nested(cfg: Mapping[str, Any], keys: list[str], default: Any = None) -> Any:
    """Safely get a nested config value."""
    current: Any = cfg
    for key in keys:
        if not isinstance(current, Mapping) or key not in current:
            return default
        current = current[key]
    return current


def require_nested(cfg: Mapping[str, Any], keys: list[str]) -> Any:
    value = get_nested(cfg, keys, default=None)
    if value is None:
        dotted = ".".join(keys)
        raise ConfigError(f"Missing required config field: {dotted}")
    return value


_KEY_RE = re.compile(r"^[A-Za-z0-9_\-]+\s*:")


def _parse_simple_yaml(text: str) -> dict[str, Any]:
    """Parse the small YAML subset used by CatConGraph config files.

    This is not a replacement for PyYAML; it is a dependency-tolerant fallback
    for ordinary CatConGraph configs.
    """
    rows: list[tuple[int, str]] = []
    for raw in text.splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        content = _strip_inline_comment(raw.rstrip())
        if not content.strip():
            continue
        indent = len(content) - len(content.lstrip(" "))
        rows.append((indent, content.strip()))
    if not rows:
        return {}
    value, index = _parse_block(rows, 0, rows[0][0])
    if index != len(rows):
        raise ConfigError(f"Could not parse config near line content: {rows[index][1]!r}")
    if not isinstance(value, dict):
        raise ConfigError("Top-level config must be a mapping.")
    return value


def _parse_block(rows: list[tuple[int, str]], index: int, indent: int) -> tuple[Any, int]:
    if index >= len(rows):
        return {}, index
    if rows[index][0] < indent:
        return {}, index
    if rows[index][0] == indent and rows[index][1].startswith("- "):
        return _parse_list(rows, index, indent)
    return _parse_mapping(rows, index, indent)


def _parse_mapping(rows: list[tuple[int, str]], index: int, indent: int) -> tuple[dict[str, Any], int]:
    mapping: dict[str, Any] = {}
    while index < len(rows):
        row_indent, content = rows[index]
        if row_indent < indent:
            break
        if row_indent > indent:
            raise ConfigError(f"Unexpected indentation near: {content!r}")
        if content.startswith("- "):
            break
        key, value_text = _split_key_value(content)
        index += 1
        if value_text == "":
            if index < len(rows) and rows[index][0] > row_indent:
                value, index = _parse_block(rows, index, rows[index][0])
            else:
                value = {}
        else:
            value = _parse_scalar(value_text)
        mapping[key] = value
    return mapping, index


def _parse_list(rows: list[tuple[int, str]], index: int, indent: int) -> tuple[list[Any], int]:
    values: list[Any] = []
    while index < len(rows):
        row_indent, content = rows[index]
        if row_indent < indent:
            break
        if row_indent != indent or not content.startswith("- "):
            break
        item_text = content[2:].strip()
        index += 1
        if item_text == "":
            if index < len(rows) and rows[index][0] > row_indent:
                item, index = _parse_block(rows, index, rows[index][0])
            else:
                item = None
        elif _looks_like_inline_mapping(item_text):
            key, value_text = _split_key_value(item_text)
            item = {key: _parse_scalar(value_text) if value_text else {}}
            if index < len(rows) and rows[index][0] > row_indent:
                nested, index = _parse_block(rows, index, rows[index][0])
                if isinstance(nested, dict):
                    item.update(nested)
                else:
                    raise ConfigError(f"List item mapping cannot be followed by a non-mapping block: {item_text!r}")
        else:
            item = _parse_scalar(item_text)
        values.append(item)
    return values, index


def _split_key_value(content: str) -> tuple[str, str]:
    in_single = False
    in_double = False
    for i, ch in enumerate(content):
        if ch == "'" and not in_double:
            in_single = not in_single
        elif ch == '"' and not in_single:
            in_double = not in_double
        elif ch == ":" and not in_single and not in_double:
            key = content[:i].strip()
            value = content[i + 1 :].strip()
            if not key:
                raise ConfigError(f"Empty key in config line: {content!r}")
            return key, value
    raise ConfigError(f"Expected key: value line in config, got: {content!r}")


def _strip_inline_comment(line: str) -> str:
    in_single = False
    in_double = False
    escaped = False
    for i, ch in enumerate(line):
        if escaped:
            escaped = False
            continue
        if ch == "\\":
            escaped = True
            continue
        if ch == "'" and not in_double:
            in_single = not in_single
        elif ch == '"' and not in_single:
            in_double = not in_double
        elif ch == "#" and not in_single and not in_double:
            if i == 0 or line[i - 1].isspace():
                return line[:i].rstrip()
    return line


def _looks_like_inline_mapping(text: str) -> bool:
    return bool(_KEY_RE.match(text))


def _parse_scalar(value: str) -> Any:
    value = value.strip()
    if value == "":
        return ""
    lowered = value.lower()
    if lowered in {"null", "none", "~"}:
        return None
    if lowered == "true":
        return True
    if lowered == "false":
        return False
    if value in {"[]", "{}"}:
        return [] if value == "[]" else {}
    if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
        try:
            return ast.literal_eval(value)
        except Exception:
            return value[1:-1]
    if value.startswith("[") and value.endswith("]"):
        try:
            parsed = ast.literal_eval(value)
        except Exception as exc:
            raise ConfigError(f"Could not parse inline list: {value!r}") from exc
        if not isinstance(parsed, list):
            raise ConfigError(f"Expected inline list, got: {value!r}")
        return parsed
    try:
        if re.match(r"^[+-]?\d+$", value):
            return int(value)
        if re.match(r"^[+-]?(\d+\.\d*|\d*\.\d+)([eE][+-]?\d+)?$", value) or re.match(r"^[+-]?\d+[eE][+-]?\d+$", value):
            return float(value)
    except Exception:
        pass
    return value
